--snippet{"name":"cols from info schema", "category":"sql"}

DECLARE @COLS  AS NVARCHAR(MAX)=''; 
SELECT @COLS = @COLS + COLUMN_NAME + ',' FROM (SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='fsma_Activities' AND COLUMN_NAME NOT LIKE '%PK_%') vw
SELECT @COLS = substring(@COLS, 0, LEN(@COLS)) --trim "," at end
SELECT @COLS 

--//snippet 


DECLARE @SRC NVARCHAR(55) = 'aspnet_Profile'
DECLARE @DICT TABLE (ROWNUM INT IDENTITY (1, 1) PRIMARY KEY NOT NULL , KY INT, VL NVARCHAR(4000))

DECLARE @RowCnt INT = 0
INSERT INTO @DICT (KY,VL)
SELECT ORDINAL_POSITION, COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@SRC
DECLARE @MaxRows INT=(SELECT COUNT(*) FROM @DICT)
WHILE @RowCnt <= @MaxRows
BEGIN
DECLARE @PKEY INT = (SELECT KY FROM @DICT WHERE ROWNUM = @RowCnt)
DECLARE @VL NVARCHAR(4000) = (SELECT VL FROM @DICT WHERE ROWNUM = @RowCnt)
PRINT @VL
SELECT @RowCnt = @RowCnt + 1
END

 
 
 
 

DECLARE @SRC NVARCHAR(55) = 'aspnet_Users'
IF OBJECT_ID('tempdb..#MTRX') IS NOT NULL DROP TABLE #MTRX
CREATE TABLE #MTRX (ROWNUM INT IDENTITY (1, 1) PRIMARY KEY NOT NULL, KY INT, VL NVARCHAR(4000))

DECLARE @RowCnt INT = 1
INSERT INTO #MTRX (KY,VL)
SELECT ORDINAL_POSITION, COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@SRC
DECLARE @MaxRows INT =(SELECT COUNT(*) FROM #MTRX)
WHILE @RowCnt <= @MaxRows
BEGIN
DECLARE @PKEY INT = (SELECT KY FROM #MTRX WHERE ROWNUM = @RowCnt)
DECLARE @VL NVARCHAR(4000) = (SELECT VL FROM #MTRX WHERE ROWNUM = @RowCnt)

SELECT @RowCnt = @RowCnt + 1
END
IF OBJECT_ID('tempdb..#MTRX') IS NOT NULL DROP TABLE #MTRX






 
IF OBJECT_ID('tempdb..#MTRX') IS NOT NULL DROP TABLE #MTRX
CREATE TABLE #MTRX (ROWNUM INT IDENTITY (1, 1) PRIMARY KEY NOT NULL, KY INT, VL NVARCHAR(4000))
DECLARE @exe NVARCHAR(MAX) = ''
SET @exe=@exe+' DECLARE @SRC NVARCHAR(55) = ''aspnet_Users'' '
SET @exe=@exe+' DECLARE @RowCnt INT = 1 '
SET @exe=@exe+' INSERT INTO #MTRX (KY,VL) '
SET @exe=@exe+' SELECT ORDINAL_POSITION, COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@SRC '
SET @exe=@exe+' DECLARE @MaxRows INT =(SELECT COUNT(*) FROM #MTRX) '
SET @exe=@exe+' WHILE @RowCnt <= @MaxRows '
SET @exe=@exe+' BEGIN '
SET @exe=@exe+' DECLARE @PKEY INT = (SELECT KY FROM #MTRX WHERE ROWNUM = @RowCnt) '
SET @exe=@exe+' DECLARE @VL NVARCHAR(4000) = (SELECT VL FROM #MTRX WHERE ROWNUM = @RowCnt) '
SET @exe=@exe+' SELECT @RowCnt = @RowCnt + 1 '
SET @exe=@exe+' END '
EXECUTE sp_executesql @exe
SELECT KY,VL FROM #MTRX
IF OBJECT_ID('tempdb..#MTRX') IS NOT NULL DROP TABLE #MTRX









DECLARE @SRC NVARCHAR(55) = 'aspnet_Users'
DECLARE @exe NVARCHAR(MAX) = ''
IF OBJECT_ID('tempdb..#MTRX') IS NOT NULL DROP TABLE #MTRX
CREATE TABLE #MTRX (ROWNUM INT IDENTITY (1, 1) PRIMARY KEY NOT NULL, KY INT, VL NVARCHAR(4000))

DECLARE @RowCnt INT = 1
INSERT INTO #MTRX (KY,VL)
SELECT ORDINAL_POSITION, COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@SRC
DECLARE @MaxRows INT =(SELECT COUNT(*) FROM #MTRX)
WHILE @RowCnt <= @MaxRows
BEGIN
DECLARE @PKEY INT = (SELECT KY FROM #MTRX WHERE ROWNUM = @RowCnt)
DECLARE @VL NVARCHAR(4000) = (SELECT VL FROM #MTRX WHERE ROWNUM = @RowCnt)
IF @RowCnt > 1 BEGIN
SET @exe = @exe + ', '
END
SET @exe = @exe + Coalesce(@VL,'')
SELECT @RowCnt = @RowCnt + 1
END
SET @exe = 'SELECT ' + @exe + ' FROM ' + @SRC
IF OBJECT_ID('tempdb..#MTRX') IS NOT NULL DROP TABLE #MTRX
EXECUTE sp_executesql @exe


