 
IF OBJECT_ID('tempdb..#PIV') IS NOT NULL DROP TABLE #PIV 
CREATE TABLE #PIV (ROWNUM INT IDENTITY (1, 1) PRIMARY KEY NOT NULL, KY INT, VL NVARCHAR(4000))  
DECLARE @exe NVARCHAR(MAX) = ''  
DECLARE @SRC NVARCHAR(55) = 'PickLists'
DECLARE @DICT TABLE (ROWNUM INT IDENTITY (1, 1) PRIMARY KEY NOT NULL , KY INT, VL NVARCHAR(4000)) 
DECLARE @RowCnt INT = 1

INSERT INTO @DICT (KY,VL)
SELECT ORDINAL_POSITION, COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@SRC

DECLARE @MaxRows INT=(SELECT COUNT(*) FROM @DICT)
SET @exe=@exe+' INSERT INTO #PIV  VALUES '
WHILE @RowCnt <= @MaxRows
BEGIN
	IF @RowCnt > 1 BEGIN
		SET @exe = @exe + ', '
	END 
	DECLARE @PKEY NVARCHAR(4000)  = (SELECT CONVERT(NVARCHAR(5),KY) FROM @DICT WHERE ROWNUM = @RowCnt)
	DECLARE @VL NVARCHAR(4000) = (SELECT VL FROM @DICT WHERE ROWNUM = @RowCnt)
	SET @exe=@exe+' ('+@PKEY+','''+@VL+''') '
	SELECT @RowCnt = @RowCnt + 1
END 
PRINT @exe
  
EXECUTE sp_executesql @exe  
SELECT KY,VL FROM #PIV 

SELECT * FROM PickLists WHERE PK_PickListType = 8
IF OBJECT_ID('tempdb..#PIV') IS NOT NULL DROP TABLE #PIV 