SET NOCOUNT ON

DECLARE @tsrc NVARCHAR(55) = 'TIC_CloudServices' 
DECLARE @TKEY INT = 0 --12 --  1011 --  13428

DECLARE @exe NVARCHAR(MAX) = ''  
DECLARE @COLS TABLE (ROWNUM INT IDENTITY (1,1) PRIMARY KEY  , COLUMN_NAME NVARCHAR(55), DATA_TYPE NVARCHAR(55)) 
DECLARE @Cn INT = 1  
DECLARE @Rn INT = 0  
INSERT INTO @COLS (COLUMN_NAME,DATA_TYPE)
SELECT DISTINCT FIELDNAME, 
	CASE WHEN INFORMATIONSCHEMA.DATA_TYPE IS NOT NULL THEN 
		INFORMATIONSCHEMA.DATA_TYPE ELSE 
		CASE WHEN  CHARINDEX('PK_', FIELDNAME)>0 THEN 'INT'  
		WHEN CHARINDEX('FK_', FIELDNAME)>0 THEN 'INT' 
		ELSE 'NVARCHAR' END
	END AS DATA_TYPE 
FROM AUDITLOG 
	LEFT JOIN ( SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@tsrc) 
	INFORMATIONSCHEMA ON AUDITLOG.FieldName=INFORMATIONSCHEMA.COLUMN_NAME
	WHERE TABLENAME=@tsrc 
	AND (FIELDNAME LIKE '[A-Z]%' OR FIELDNAME LIKE '[a-z]%'  )  
	AND (FIELDNAME NOT LIKE '% %') AND (FIELDNAME NOT LIKE '%\%') AND (FIELDNAME NOT LIKE '%/%') AND (FIELDNAME NOT LIKE '%~%') AND (FIELDNAME NOT LIKE '%!%') AND (FIELDNAME NOT LIKE '%@%') AND (FIELDNAME NOT LIKE '%#%') AND (FIELDNAME NOT LIKE '%$%') AND (FIELDNAME NOT LIKE '%^%') AND (FIELDNAME NOT LIKE '%&%') AND (FIELDNAME NOT LIKE '%*%') AND (FIELDNAME NOT LIKE '%(%') AND (FIELDNAME NOT LIKE '%)%') AND (FIELDNAME NOT LIKE '%-%') AND (FIELDNAME NOT LIKE '%+%') AND (FIELDNAME NOT LIKE '%=%') AND (FIELDNAME NOT LIKE '%{%') AND (FIELDNAME NOT LIKE '%[%') AND (FIELDNAME NOT LIKE '%}%') AND (FIELDNAME NOT LIKE '%]%') AND (FIELDNAME NOT LIKE '%:%') AND (FIELDNAME NOT LIKE '%;%') AND (FIELDNAME NOT LIKE '%<%') AND (FIELDNAME NOT LIKE '%>%') AND (FIELDNAME NOT LIKE '%.%') AND (FIELDNAME NOT LIKE '%?%') AND (FIELDNAME NOT LIKE '%/%') AND (FIELDNAME NOT LIKE '%"%')     
-- SELECT * FROM @COLS
IF OBJECT_ID('tempdb..#UPIV') IS NOT NULL DROP TABLE #UPIV 
CREATE TABLE #UPIV (ROWNUM INT IDENTITY (1,1), RECGROUP INT, PK_PrimeKey INT, Change_Date DATETIME, PK_Agency INT, UserID INT, EditType NVARCHAR(1), String_PrimeKey NVARCHAR(255) )  
WHILE @Cn <= (SELECT COUNT(*) FROM @COLS)
BEGIN
	DECLARE @COLUMN_NAME NVARCHAR(55)=(SELECT COLUMN_NAME FROM @COLS WHERE ROWNUM=@Cn)
	DECLARE @DATA_TYPE NVARCHAR(55)=(SELECT DATA_TYPE FROM @COLS WHERE ROWNUM=@Cn)
	SET @exe=@exe+(
		SELECT CASE
		WHEN CHARINDEX('int', @DATA_TYPE)>0 THEN ' ALTER TABLE #UPIV ADD '+@COLUMN_NAME+' INT '   
		WHEN CHARINDEX('float', @DATA_TYPE)>0 THEN ' ALTER TABLE #UPIV ADD '+@COLUMN_NAME+' FLOAT(2,10) ' 
		ELSE ' ALTER TABLE #UPIV ADD '+@COLUMN_NAME+' NVARCHAR(4000) ' END ) 
	SET @Cn=@Cn+1
END
EXECUTE sp_executesql @exe 
--  SELECT * FROM #UPIV 
DECLARE @AUDITROWS TABLE (ROWNUM INT IDENTITY (1,1) PRIMARY KEY, RECGROUP INT, FIELDNAME NVARCHAR(255), FIELDVALUE NVARCHAR(4000), PK_PrimeKey INT, Change_Date DATETIME, PK_Agency INT, UserID INT, String_PrimeKey NVARCHAR(255) ) 
INSERT INTO @AUDITROWS (RECGROUP, FIELDNAME, FIELDVALUE, PK_PrimeKey, Change_Date, PK_Agency, UserID ,  String_PrimeKey)

SELECT RANK() OVER (ORDER BY PK_PrimeKey, CONVERT(NVARCHAR(10),CHANGE_DATE, 121) DESC) AS RECGROUP,
FIELDNAME, FIELDVALUE, PK_PrimeKey, CONVERT(NVARCHAR(10),CHANGE_DATE, 121) CHANGE_DATE, PK_Agency , UserID , String_PrimeKey 
FROM (-- DECLARE @tsrc NVARCHAR(255) = 'TIC_CloudServices'  
	SELECT 
	ROW_NUMBER() OVER (PARTITION BY PK_PrimeKey , MONTH(CHANGE_DATE), FIELDNAME ORDER BY PK_PrimeKey, CHANGE_DATE  DESC  ) AS RowRank, MONTH(CHANGE_DATE) mm, DAY(CHANGE_DATE) dd , 
	PK_PrimeKey, Change_Date, FIELDNAME, FIELDVALUE, PK_Agency , UserID , String_PrimeKey 
	FROM AUDITLOG WHERE TABLENAME=@tsrc 
	AND (FIELDNAME LIKE '[A-Z]%' OR FIELDNAME LIKE '[a-z]%'  ) AND (FIELDNAME NOT LIKE '% %') AND (FIELDNAME NOT LIKE '%\%') AND (FIELDNAME NOT LIKE '%/%') AND (FIELDNAME NOT LIKE '%~%') AND (FIELDNAME NOT LIKE '%!%') AND (FIELDNAME NOT LIKE '%@%') AND (FIELDNAME NOT LIKE '%#%') AND (FIELDNAME NOT LIKE '%$%') AND (FIELDNAME NOT LIKE '%^%') AND (FIELDNAME NOT LIKE '%&%') AND (FIELDNAME NOT LIKE '%*%') AND (FIELDNAME NOT LIKE '%(%') AND (FIELDNAME NOT LIKE '%)%') AND (FIELDNAME NOT LIKE '%-%') AND (FIELDNAME NOT LIKE '%+%') AND (FIELDNAME NOT LIKE '%=%') AND (FIELDNAME NOT LIKE '%{%') AND (FIELDNAME NOT LIKE '%[%') AND (FIELDNAME NOT LIKE '%}%') AND (FIELDNAME NOT LIKE '%]%') AND (FIELDNAME NOT LIKE '%:%') AND (FIELDNAME NOT LIKE '%;%') AND (FIELDNAME NOT LIKE '%<%') AND (FIELDNAME NOT LIKE '%>%') AND (FIELDNAME NOT LIKE '%.%') AND (FIELDNAME NOT LIKE '%?%') AND (FIELDNAME NOT LIKE '%/%') AND (FIELDNAME NOT LIKE '%"%')     
	-- AND PK_PrimeKey=2452
) MONTHLY_AUDITS WHERE ROWRANK=1
  
--    SELECT * FROM @AUDITROWS 
   
INSERT INTO #UPIV (RECGROUP, CHANGE_DATE, PK_PrimeKey, PK_Agency, UserID, String_PrimeKey)
SELECT DISTINCT RECGROUP, CHANGE_DATE, PK_PrimeKey, PK_Agency, UserID, String_PrimeKey  
FROM @AUDITROWS ORDER BY PK_PrimeKey ASC
  
--    SELECT * FROM #UPIV 

SET @Rn = 1 
DECLARE @RECGROUP INT = 0 
DECLARE @SQL NVARCHAR(MAX) = ''
DECLARE @EXEC NVARCHAR(MAX) = ''
WHILE @Rn < (SELECT COUNT(*) FROM @AUDITROWS)
BEGIN
	SET @COLUMN_NAME=(SELECT ISNULL(FIELDNAME,'') FROM @AUDITROWS WHERE ROWNUM=@Rn)
	SET @DATA_TYPE=(SELECT DISTINCT DATA_TYPE FROM @COLS WHERE COLUMN_NAME=@COLUMN_NAME)
	SET @RECGROUP=(SELECT RECGROUP FROM @AUDITROWS WHERE ROWNUM=@Rn) 
	DECLARE @PK_PrimeKey INT =(SELECT PK_PrimeKey FROM @AUDITROWS WHERE ROWNUM=@Rn) 
	DECLARE @Change_Date DATETIME=(SELECT Change_Date FROM @AUDITROWS WHERE ROWNUM=@Rn)
	DECLARE @NFIELDVALUE NVARCHAR(4000)=(SELECT CONVERT(NVARCHAR(4000),REPLACE(ISNULL(FIELDVALUE,''),'''', '')) FROM @AUDITROWS WHERE ROWNUM=@Rn)

	DECLARE @PARAMS NVARCHAR(255) = ' @RECGROUP INT , @'+@COLUMN_NAME+' NVARCHAR(4000)' 
	DECLARE @ISNUM bit = (SELECT ISNUMERIC(@NFIELDVALUE)) 
	BEGIN TRY    
		SET @EXEC=@EXEC+' UPDATE #UPIV SET '+ CONVERT(NVARCHAR(255),@COLUMN_NAME)+'=N'''+CONVERT(NVARCHAR(255), @NFIELDVALUE) + ''''  
		SET @EXEC=@EXEC+' WHERE PK_PrimeKey='+ CONVERT(NVARCHAR(5),@PK_PrimeKey)+ ' AND RECGROUP='+ CONVERT(NVARCHAR(23),@RECGROUP)+ ' AND CHANGE_DATE='''+ CONVERT(NVARCHAR(23),@CHANGE_DATE, 121)+''';';  
	END TRY  
	BEGIN CATCH   
			PRINT @EXEC;
			THROW 
	END CATCH  
	SET @Rn=@Rn+1
END   
PRINT @EXEC
--EXECUTE sp_executesql @EXEC
 
IF @TKEY = 0 BEGIN 
	SELECT * FROM @AUDITROWS
	SELECT * FROM #UPIV 
	--SELECT * FROM AUDITLOG WHERE TABLENAME=@tsrc 
END
IF @TKEY <> 0 BEGIN 
 SELECT * FROM AUDITLOG WHERE TABLENAME=@tsrc AND PK_PrimeKey = @TKEY
 SELECT * FROM #UPIV  WHERE PK_PrimeKey = @TKEY
END 
IF OBJECT_ID('tempdb..#UPIV') IS NOT NULL DROP TABLE #UPIV 
