 
UPDATE BOD_Snapshot  
SET BOD_Snapshot.EstimatedRemDate = AL.FieldValue
FROM BOD_Snapshot BOD
INNER JOIN AUDITLOG AL ON BOD.PK_BOD=AL.PK_PrimeKey AND TABLENAME='BOD' AND FIELDNAME='EstimatedRemDate'

SELECT * FROM BOD_Snapshot

SELECT * FROM AUDITLOG WHERE TABLENAME = 'BOD' 
--SELECT DISTINCT COUNT (CHANGE_Date) , TABLENAME FROM AuditLog GROUP BY TABLENAME WHERE TABLENAME='BOD'