

DECLARE @exe NVARCHAR(MAX) = ''  
DECLARE @C TABLE (Cn INT IDENTITY (1, 1) PRIMARY KEY NOT NULL , CNAME NVARCHAR(255)) 
DECLARE @Cn INT = 1  
DECLARE @Rn INT = 1  
INSERT INTO @C
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PickLists'

IF OBJECT_ID('tempdb..#R') IS NOT NULL DROP TABLE #R 
CREATE TABLE #R (Rn INT IDENTITY (1, 1))  
SELECT ROW_NUMBER() OVER(ORDER BY PK_Picklist ASC) AS Row# , * FROM PickLists WHERE PK_PickListType = 8

WHILE @Cn <= (SELECT COUNT(*) FROM @C)
BEGIN
	DECLARE @CNAM NVARCHAR(255) = (SELECT CNAME FROM @C WHERE Cn=@Cn)
	DECLARE @stm NVARCHAR(4000) = (SELECT 'ALTER TABLE #R ADD ' + @CNAM  + '  NVARCHAR(255) ') 
	EXECUTE sp_executesql @stm 
	--SET @exe=@exe+' ('+@PKEY+','''+@VL+''') '
	SELECT @Cn = @Cn + 1
END 
--PRINT @exe

SELECT * FROM #R
 
